# Neural Network and Deep Learning

---

## Perceptron

Artificial neurons (also called Perceptrons, Units or Nodes) are the simplest elements or building blocks in a neural network. They are inspired by biological neurons that are found in the human brain.

Perceptron is a single layer neural network and a multi-layer perceptron is called Neural Networks.


![](https://miro.medium.com/max/1200/1*hkYlTODpjJgo32DoCOWN5w.png)

---

## Layer in Neural Network

In neural networks, a hidden layer is located between the input and output of the algorithm, in which the function applies weights to the inputs and directs them through an activation function as the output. In short, the hidden layers perform nonlinear transformations of the inputs entered into the network. Hidden layers vary depending on the function of the neural network, and similarly, the layers may vary depending on their associated weights.

![](https://www.druva.com/assets/blog-graphic_visualizing-neural-networks-2048x840.jpg)

## Neural Network Intuition

![](https://github.com/BenedictusAryo/konten_image/raw/master/crop_NN.jpg)

## Components of Neural Network

1. **X** = Input data
2. **Y** = Output Data
3. **Z** = Hidden Layer
4. **W** = Weight that connect between nodes
5. **b** = Bias (Constant)
6. **a** = Activation Function (Non Linear Function)

---

## Manual Sample Calculation of Neural Network


In [52]:
# Learning rate
alpha = 0.1

# Input Layer
x1 = 0.7
x2 = 0.8
x3 = 0.9

# Output layer
yd6 = 0

# Initialized weight
w14 = 0.5
w15 = 0.6
w24 = 0.3
w25 = 1.1
w34 = -1.0
w35 = 0.1
w46 = -1.1
w56 = -0.7

# Bias / Theta & threshold
thres1 = thres2 = thres3 = -1
theta4 = 0.2
theta5 = 0.3
theta6 = 0.4

# Activation Function
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return 1 / (1 + np.exp(-x))* (1 - 1 / (1 + np.exp(-x)))

In [53]:
# Forward pass
sum_y4 = x1*w14 + x2*w24 + x3*w34 + thres1*theta4
sum_y5 = x1*w15 + x2*w25 + x3*w35 + thres2*theta5
y4 = sigmoid(sum_y4)
y5 = sigmoid(sum_y5)
sum_y6 = y4*w46 + y5*w56 + thres3*theta6
y6 = sigmoid(sum_y6)
print(f"Sum y4: {sum_y4}, sum y5: {sum_y5}, sum y6: {sum_y6}")
print(f"Y4: {y4}, Y5: {y5}, Y6: {y6}")

Sum y4: -0.51, sum y5: 1.09, sum y6: -1.3365800832096726
Y4: 0.3751935255315707, Y5: 0.7483817216070642, Y6: 0.20807302520657042


In [31]:
# Error calculation
error = yd6 - y6
error

-0.20807302520657042

In [44]:
# Gradient error output Y6
error_grad6 = y6*(1-y6)*(yd6-y6)
error_grad6

-0.03428599040302067

In [58]:
# Backward Pass output Y6
grad46 = alpha * y4 * error_grad6
grad56 = alpha * y5 * error_grad6
grad_bias6 = alpha * theta6 * error_grad6
print(f"grad4 = {grad46}, grad5 = {grad56}, grad_bias = {grad_bias6}")

grad4 = -0.0012863881615650925, grad5 = -0.0025659008524815887, grad_bias = -0.001371439616120827


In [46]:
# Gradient error output Y4 Y5
# Loss Calculation MSE
gradY4 = y4*(1-y4)*error_grad6*w46
gradY5 = y5*(1-y5)*error_grad6*w56
print(f"grad4 = {gradY4}, grad5 = {gradY5}")

grad4 = 0.008841180172279505, grad5 = 0.004519392885198686


In [55]:
#Weight connection  Backward Pass output Y4
grad14 = alpha * x1 * gradY4
grad24 = alpha * x2 * gradY4
grad34 = alpha * x3 * gradY4
grad_bias4 = alpha * theta4 * gradY4
print(f"grad 14 : {grad14}, grad 24 : {grad24}, grad 34 : {grad34}, grad_bias4 : {grad_bias4}")

grad 14 : 0.0006188826120595653, grad 24 : 0.0007072944137823606, grad 34 : 0.0007957062155051556, grad_bias4 : 0.00017682360344559015


In [57]:
#Weight connection  Backward Pass output Y5
grad15 = alpha * x1 * gradY5
grad25 = alpha * x2 * gradY5
grad35 = alpha * x3 * gradY5
grad_bias5 = alpha * theta5 * gradY4
print(f"grad 15 : {grad15}, grad 25 : {grad25}, grad 35 : {grad35}, grad_bias5 : {grad_bias5}")

grad 15 : 0.00031635750196390796, grad 25 : 0.00036155143081589494, grad 35 : 0.00040674535966788176, grad_bias5 : 0.0002652354051683852


In [59]:
#Update vakues 
w14 = w14 + grad14
w15 = w15 + grad15
w24 = w24 + grad24
w25 = w25 + grad25
w34 = w34 + grad34
w35 = w35 + grad35
w46 = w46 + grad46
w56 = w56 + grad56
theta4 = theta4 + grad_bias4
theta5 = theta5 + grad_bias5
theta6 = theta6 + grad_bias6

print("Updated weights and bias:")
print("w14 =", w14)
print("w15 =", w15)
print("w24 =", w24)
print("w25 =", w25)
print("w34 =", w34)
print("w35 =", w35)
print("w46 =", w46)
print("w56 =", w56)
print("theta4 =", theta4)
print("theta5 =", theta5)
print("theta6 =", theta6)

Updated weights and bias:
w14 = 0.5006188826120596
w15 = 0.6003163575019639
w24 = 0.30070729441378236
w25 = 1.100361551430816
w34 = -0.9992042937844948
w35 = 0.10040674535966788
w46 = -1.101286388161565
w56 = -0.7025659008524815
theta4 = 0.2001768236034456
theta5 = 0.30026523540516836
theta6 = 0.39862856038387917


## Neural Network Manual using Numpy

In [8]:
import numpy as np
import pandas as pd

In [5]:
class NeuralNetwork:
    def __init__(self, x, y, learning_rate=0.1):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 4)
        self.weights2 = np.random.rand(4, 1)
        self.bias1 = np.zeros((1, 4))
        self.bias2 = np.zeros((1, 1))
        self.y = y
        self.output = np.zeros(self.y.shape)
        self.learning_rate = learning_rate

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return 1 / (1 + np.exp(-x)) * (1 - 1 / (1 + np.exp(-x)))

    def forwardprop(self):
        self.layer1 = self.sigmoid(np.dot(self.input, self.weights1) + self.bias1)
        self.output = self.sigmoid(np.dot(self.layer1, self.weights2) + self.bias2)

    def backprop(self):
        error = self.y - self.output
        d_output = error * self.sigmoid_derivative(self.output)
        error_layer1 = d_output.dot(self.weights2.T)
        d_layer1 = error_layer1 * self.sigmoid_derivative(self.layer1)
        self.d_output = d_output
        self.error_layer1 = error_layer1
        
    def update_weights(self):
        self.weights2 += self.layer1.T.dot(self.d_output) * self.learning_rate
        self.weights1 += self.input.T.dot(self.d_layer1) * self.learning_rate
        self.bias2 += np.sum(self.d_output, axis=0, keepdims=True) * self.learning_rate
        self.bias1 += np.sum(self.d_layer1, axis=0, keepdims=True) * self.learning_rate

    def fit(self, X, y):
        self.output = np.zeros(y.shape)
        self.input = X
        self.y = y
        self.forwardprop()
        self.backprop()
        self.update_weights()

    def calculate_loss(self):
        error = self.y - self.output
        return np.mean(error**2)

In [16]:
class NeuralNetwork:
    def __init__(self, x, y, learning_rate=0.1):
        self.input = x
        self.weights1 = np.random.rand(self.input.shape[1], 4)
        self.weights2 = np.random.rand(4, 1)
        self.bias1 = np.zeros((1, 4))
        self.bias2 = np.zeros((1, 1))
        self.y = y
        self.output = np.zeros(self.y.shape)
        self.learning_rate = learning_rate

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1 - x)

    def feedforward(self):
        self.layer1 = self.sigmoid(np.dot(self.input, self.weights1) + self.bias1)
        self.output = self.sigmoid(np.dot(self.layer1, self.weights2) + self.bias2)

    def backprop(self):
        error = self.y - self.output
        d_output = error * self.sigmoid_derivative(self.output)
        error_layer1 = d_output.dot(self.weights2.T)
        d_layer1 = error_layer1 * self.sigmoid_derivative(self.layer1)
        self.weights2 += self.layer1.T.dot(d_output) * self.learning_rate
        self.weights1 += self.input.T.dot(d_layer1) * self.learning_rate
        self.bias2 += np.sum(d_output, axis=0, keepdims=True) * self.learning_rate
        self.bias1 += np.sum(d_layer1, axis=0, keepdims=True) * self.learning_rate

    def train(self, X, y):
        self.output = np.zeros(y.shape)
        self.input = X
        self.y = y
        self.feedforward()
        self.backprop()

    def calculate_loss(self):
        error = self.y - self.output
        return np.mean(error**2)

In [13]:
# OR Dataset
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = np.array([[0], [1], [1], [1]])
df = pd.DataFrame(X, columns=['x1','x2'])
df['y'] = y
df

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [24]:
nn = NeuralNetwork(X,y)
nn.train(X,y)

for i in range(1000):
    nn.train(X, y)

print("Loss: ", nn.calculate_loss())
print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" + str(nn.output))

Loss:  0.030189432724354603
Input: 
[[0 0]
 [0 1]
 [1 0]
 [1 1]]
Actual Output: 
[[0]
 [1]
 [1]
 [1]]
Predicted Output: 
[[0.27592769]
 [0.85657558]
 [0.84855604]
 [0.96659637]]


### Links:
* https://towardsdatascience.com/what-the-hell-is-perceptron-626217814f53#:~:text=Perceptron%20is%20a%20single%20layer,classify%20the%20given%20input%20data
* https://towardsdatascience.com/the-concept-of-artificial-neurons-perceptrons-in-neural-networks-fab22249cbfc
* https://www.druva.com/blog/understanding-neural-networks-through-visualization/
* https://stackoverflow.com/questions/2480650/what-is-the-role-of-the-bias-in-neural-networks